Katie
KevinDeMars/db-proj pull request #1
Opened 2021-10-22 20:49 UTC by kjwok

Added implementation for query processor: select, project, cross product
Implemented cross product
Implemented half of select (waiting for btree clarification)

2021-10-23 16:19 UTC, KevinDeMars requested changes

2021-10-23 16:19 UTC, KevinDeMars commented on db/operators/cross_product.py
> +    r1[-1] = r1[-1].strip()
What's this do? Doesn't it strip whitespace from only the last column name from each relation?

2021-10-23 16:19 UTC, KevinDeMars commented on db/operators/cross_product.py
> +    attrs = r1 + r2
Needs to handle case where rel1 and rel2 have same column name. For example, add 'r1.' in front of r1's column names and same for r2.

2021-10-23 16:19 UTC, KevinDeMars commented on db/operators/join.py
> +    attrs = _attributes(r1, r2)
This is only the attributes they have in common. Natural join includes all attributes from both r1 and r2.

2021-10-23 16:19 UTC, KevinDeMars commented on db/operators/select.py
> +    return -1
Identical to get_attr_index, just use that

2021-10-23 16:19 UTC, KevinDeMars commented on db/operators/select.py
> +    if isinstance(attrs[1], int):
Will never be true because it gets passed as a string representing an int, like "5" (with quotes). I don't remember how to check if a string is a valid int in python, but we need to do that.

2021-10-24 18:31 UTC, kjwok commented on db/operators/cross_product.py
> +    r1[-1] = r1[-1].strip()
Yeah, when I call .col_names, the last column has an endline for some reason. I couldn't figure out how to change that, so I was using strip() to get rid of it.

2021-10-24 18:31 UTC, kjwok commented on db/operators/join.py
> +    attrs = _attributes(r1, r2)
Yeah, I haven't worked on join yet. This is older code

2021-10-29 23:08 UTC, merged